FROM alpine:3.20.0

ENV TRACCAR_VERSION 6.2

WORKDIR /opt/traccar

RUN set -ex && \
    apk add --no-cache --no-progress openjdk11-jre-headless wget nano && \
    wget -qO /tmp/traccar.zip http://bbs.atoo.top:8081/files/traccar-other-6.2-amap.zip && \
    unzip -qo /tmp/traccar.zip -d /opt/traccar && \
    rm /tmp/traccar.zip && \
    apk del wget

ENTRYPOINT ["java", "-Xms1g", "-Xmx1g", "-Djava.net.preferIPv4Stack=true"]

CMD ["-jar", "tracker-server.jar", "conf/traccar.xml"]
