FROM alpine AS package
ARG TRACCAR_VERSION=6.15.0
RUN apk add --no-cache curl
RUN curl -L -o /tmp/traccar.zip http://home.atoo.top:8081/traccar/traccar-other-$TRACCAR_VERSION-amap.zip
RUN unzip -qo /tmp/traccar.zip -d /traccar

FROM eclipse-temurin:22 AS jdk
RUN jlink --add-modules java.se,jdk.charsets,jdk.crypto.ec,jdk.unsupported \
    --strip-debug --no-header-files --no-man-pages --compress=2 --output /jre

FROM debian:stable-slim
COPY --from=package /traccar /opt/traccar
COPY --from=jdk /jre /opt/traccar/jre
WORKDIR /opt/traccar
ENTRYPOINT ["/opt/traccar/jre/bin/java", "-XX:+ExitOnOutOfMemoryError"]
CMD ["-jar", "tracker-server.jar", "conf/traccar.xml"]
